# Project: Funciones_C++
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Funciones_NumeroMayor.o "Plantillas\ de\ funcion.o" Funciones_multiplicacion.o
LINKOBJ  = Funciones_NumeroMayor.o "Plantillas de funcion.o" Funciones_multiplicacion.o
LIBS     = -L"C:/Users/Kiana/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/Kiana/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Kiana/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Kiana/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Kiana/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Kiana/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Kiana/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Kiana/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Kiana/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Funciones_C++.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Funciones_NumeroMayor.o: Funciones_NumeroMayor.cpp
	$(CPP) -c Funciones_NumeroMayor.cpp -o Funciones_NumeroMayor.o $(CXXFLAGS)

"Plantillas\ de\ funcion.o": Plantillas\ de\ funcion.cpp
	$(CPP) -c "Plantillas de funcion.cpp" -o "Plantillas de funcion.o" $(CXXFLAGS)

Funciones_multiplicacion.o: Funciones_multiplicacion.cpp
	$(CPP) -c Funciones_multiplicacion.cpp -o Funciones_multiplicacion.o $(CXXFLAGS)
